<?php

class Image
{
    public static $resizing_enabled = true;

    public static function geometry()
    {
        echo "800*600";
    }
}

class ProfileImage extends Image
{
    public static function geometry()
    {
        if(self::$resizing_enabled)
        {
            echo "100*100";
        }
        else
        {
            parent::geometry(); // TODO: Change the autogenerated stub
        }
    }
}

echo "The values for the Parent class: ";
echo Image::geometry()."<br/>";
echo "The values for the subclass: ";
echo ProfileImage::geometry()."<br/>";
echo "We could observe that as default values inherited from the parent class are overwritten.";

echo "<br/><br/>If we reset the value for the property 'resizing_enabled' in subclass.<br/>";
ProfileImage::$resizing_enabled = false;
echo "<br/>And the result is: ";
echo ProfileImage::geometry();