<?php

class Chef
{
    public static function make_dinner()
    {
        echo "Cook food.";
    }
}

class AmateurChef extends Chef
{
    public static function make_dinner()
    {
        echo "READ recipe.";
        parent::make_dinner(); // TODO: Change the autogenerated stub
        echo "Clean up mess.";
    }
}

echo Chef::make_dinner();
echo "<br/>";
echo AmateurChef::make_dinner();
